name: Setup pnpm Reusable Workflow
description: Install pnpm and dependencies

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: '9.15'
        run_install: false

    - name: Install Dependencies
      shell: sh
      run: pnpm install
