name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.*'
      - package.json
      - yarn.lock

  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.*'
      - package.json
      - yarn.lock

  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5
          run_install: false

      - name: Read .nvmrc
        run: |
          NODE_VERSION=$(cat .nvmrc)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

      - name: Run typechecker
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test:no-watch

      - name: Build
        run: pnpm build
