name: Setup pnpm Reusable Workflow

on:
  workflow_call:
    inputs:
      pnpm_version:
        description: 'Version of pnpm to install'
        required: true
        default: '9.15'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm_version }}
          run_install: false
      
      - name: Install Dependencies
        run: pnpm install
